name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest']
        python-version: [ '3.7', '3.8', '3.9', '3.10', 'pypy-3.7']
        exclude:
          - os: "windows-latest"
            python-version: "pypy-3.7"
          - os: "macos-latest"
            python-version: "3.8"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run base setup actions
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install Linux dependencies
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo apt-get update
          sudo apt-get install texlive-plain-generic inkscape texlive-xetex

          # pandoc is not up to date in the ubuntu repos, so we install directly
          wget https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-1-amd64.deb && sudo dpkg -i pandoc-2.14.2-1-amd64.deb

      - name: Install package dependencies
        shell: bash
        run: |
          pip install codecov --user
          pip install -e ".[execute,serve,test]" --user
          pip install check-manifest
          python -m ipykernel.kernelspec --user
          # many things installed in --users need this to be in $PATH
          echo "/Users/runner/.local/bin" >> $GITHUB_PATH

      - name: List installed packages
        run: |
          pip freeze
          pip check

      - name: Run tests with coverage
        if: ${{ !startsWith(matrix.python-version, 'pypy') && !startsWith(runner.os, 'Windows')  }}
        shell: bash
        env:
          PYTHONWARNINGS: default
        run: |
          check-manifest --ignore "share/**"
          # See https://github.com/pyppeteer/pyppeteer/pull/321
          pip install -U websockets --user
          # cd so we test the install, not the repo
          cd $HOME
          pytest --cov nbconvert -v --pyargs nbconvert

      - name: Run tests on pypy and Windows
        if: ${{ startsWith(matrix.python-version, 'pypy') || startsWith(runner.os, 'Windows')  }}
        shell: bash
        run: |
          
          # cd so we test the install, not the repo
          cd $HOME
          # See https://github.com/pyppeteer/pyppeteer/pull/321
          pip install -U websockets --user
          pytest -v --pyargs nbconvert

      - name: Code coverage
        run: codecov
